---
# file: main.yml

- name: Elasticsearch latest | Prepare elasticsearch directory /home/wenba/elasticsearch-version
  remote_user: wenba
  file: path={{ elasticsearch_installed_directory }} owner=wenba group=wenba state=directory recurse=yes

- name: Elasticsearch latest | Link elasticsearch to latest version
  remote_user: wenba
  sudo: yes
  file: src={{ elasticsearch_installed_directory }} dest=/home/wenba/elasticsearch owner=wenba group=wenba state=link force=yes

- name: Elasticsearch latest | Copy latest elasticsearch original package
  remote_user: wenba
  sudo: yes
  copy: src={{ elasticsearch_latest_package }} dest={{ package_original_directory}}/{{ elasticsearch_latest_package }} owner=wenba group=wenba mode=0644
  
- name: Elasticsearch latest | Untar latest elasticsearch package
  remote_user: wenba
  sudo: yes
  shell: /bin/tar xvf {{ package_original_directory}}/{{ elasticsearch_latest_package }} -C {{ package_untar_directory}} creates={{ elasticsearch_installed_directory }}/config/elasticsearch.yml

- name: Elasticsearch latest | Copy configuration file elasticsearch.yml
  remote_user: wenba
  sudo: yes
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_latest_installed_directory }}/config/elasticsearch.yml owner=wenba group=wenba mode=0664

- name: Elasticsearch latest | Ensure elasticsearch directory owner as wenba
  remote_user: wenba
  sudo: yes
  file: path={{ elasticsearch_installed_directory }} owner=wenba group=wenba state=directory recurse=yes

- name: Elasticsearch latest | Start elasticsearch service 
  remote_user: wenba
  sudo: yes
  shell: "/bin/bash {{ elasticsearch_latest_installed_directory }}/bin/elasticsearch -d && sleep 2"

- name: Elasticsearch latest | Start elasticsearch mapping
  remote_user: wenba
  sudo: yes
  shell: /bin/bash {{ elasticsearch_latest_installed_directory }}/setup.sh
  when: ansible_hostname == "{{ elasticsearch_mapping_host }}"

- name: Elasticsearch latest | Check elasticsearch service ok
  remote_user: wenba
  sudo: yes
  shell: curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
  register: elasticsearch_status
  ignore_errors: yes
