---
# file: main.yml

- name: Nginx latest | Add group nginx
  remote_user: wenba
  sudo: yes
  group: name=nginx state=present

- name: Nginx latest | Add user nginx
  remote_user: wenba
  sudo: yes
  user: name=nginx shell=/sbin/nologin group=nginx createhome=no state=present

- name: Nginx latest | Prepare nginx directory /home/wenba/nginx-version
  remote_user: wenba
  file: path={{ nginx_installed_directory }} owner={{ nginx_user }} group={{ nginx_user }} state=directory recurse=yes

- name: Nginx latest | Link nginx to latest version
  remote_user: wenba
  sudo: yes
  file: src={{ nginx_installed_directory }} dest=/home/wenba/nginx owner={{ nginx_user }} group={{ nginx_user }} state=link force=yes

- name: Nginx latest | Prepare nginx directory /home/wenba/nginx/conf.d and logs
  remote_user: wenba
  sudo : yes
  file: path={{ item }} owner={{ nginx_user }} group={{ nginx_user }} state=directory recurse=yes
  with_items:
    - "{{ nginx_latest_installed_directory }}/etc/conf.d" 
    - "{{ nginx_latest_installed_directory }}/logs" 

- name: Nginx latest | Copy latest nginx original package
  remote_user: wenba
  sudo: yes
  copy: src={{ nginx_latest_package }} dest={{ package_original_directory}}/{{ nginx_latest_package }} owner={{ nginx_user }} group={{ nginx_user }} mode=0644
  
- name: Nginx latest | Untar latest nginx package
  remote_user: wenba
  sudo: yes
  shell: /bin/tar zxvf {{ package_original_directory}}/{{ nginx_latest_package }} -C {{ package_untar_directory }}

- name: Nginx latest | Installed latest nginx 
  remote_user: wenba
  sudo: yes
  script: nginx_install.sh {{ package_untar_directory }}/{{ nginx_version }} {{ nginx_latest_installed_directory }} creates={{ nginx_latest_installed_directory }}/etc/nginx.conf

- name: Nginx latest | Copy init.d start script nginx 
  remote_user: wenba
  sudo: yes
  copy: src=nginx_init_start.sh dest=/etc/init.d/nginx owner=root group=root mode=0755 

- name: Nginx latest | Copy configuration file nginx.conf
  remote_user: wenba
  sudo: yes
  template: src=nginx_nginx.conf.j2 dest={{ nginx_latest_installed_directory }}/etc/nginx.conf owner={{ nginx_user }} group={{ nginx_user }} mode=0644
  notify: restart nginx

- name: Nginx latest | Copy configuration file www.conf
  remote_user: wenba
  sudo: yes
  template: src=www.conf.j2 dest={{ nginx_latest_installed_directory }}/etc/conf.d/www.conf owner={{ nginx_user }} group={{ nginx_user }} mode=0644
  notify: restart nginx

- name: Nginx latest | Prepare nginx directory /home/wenba/nginx-version
  remote_user: wenba
  file: path={{ nginx_installed_directory }} owner={{ nginx_user }} group={{ nginx_user }} state=directory recurse=yes

- name: Nginx latest | Check service daemon
  service: name=nginx state=restarted enabled=yes
