---
# file: auth.yml

- name: auth | Change SSH port
  sudo: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#Port 22" line="Port 9922" state=present
  notify: restart ssh

- name: auth | Disallow root SSH access
  sudo: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh

- name: auth | Disallow PasswordAuthentication
  sudo: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh
  when: ansible_hostname != "image" and ansible_hostname != "compute-login"

- name: auth | Disallow root SSH access
  sudo: yes
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#PubkeyAuthentication" line="PubkeyAuthentication yes" state=present
  notify: restart ssh

- name: auth | Change SSH Client Connect port
  sudo: yes
  lineinfile: dest=/etc/ssh/ssh_config insertafter="^Host" line="Port 9922" state=present
