---
# file: logwatch.yml
- name: logwatch | install logwatch
  sudo: yes
  yum: name=logwatch state=installed

- name: logwatch | make logwatch mail daily
  sudo: yes
  lineinfile: dest=/etc/cron.daily/00logwatch regexp="^/usr/sbin/logwatch" line="/usr/sbin/logwatch high --print | mailx -A zabbix -s \"{{ ffm_logwatch_email_title}}\" {{ ffm_logwatch_email }} &>/dev/null" state=present create=yes mode=755
