---
# file: main.yml

- name: Prepare acceleration on all servers
  sudo: yes
  yum: name=python-keyczar state=present
  tags: setup


- include: hostname.yml
- include: charset.yml
- include: sudo_vim.yml
- include: selinux.yml
- include: system.yml
- include: network.yml
  when: ansible_default_ipv4.network == "10.9.*.*" and outer_ip == "no"
- include: updates.yml
- include: users.yml
- include: package_directory.yml
- include: mailx.yml
- include: logwatch.yml
- include: fail2ban.yml
- include: iptables.yml
- include: auth.yml
