---
# file: system.yml

- name: system | Modify the number of open files by one process
  remote_user: wenba
  sudo: yes
  shell: ulimit -SHn 65535 creates=/etc/security/limits.d/nofile.conf

- name: system | Write nofile into the system file
  remote_user: wenba
  sudo: yes
  template: src=nofile.conf.j2 dest=/etc/security/limits.d/nofile.conf owner=root group=root mode=0644
