- name: install zabbix-agent-2.2
  remote_user: wenba
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - "{{ zabbix_2 }}"
   - "{{ zabbix_agent_2 }}"
   - "{{ zabbix_sender_2 }}"
