---
# File: main.yml
# Type: task
# Part: PHP5


## Install PHP5
- name: PHP5 | Install package
  remote_user: wenba
  sudo: yes
  yum: name=php state={{ php5_yum_state }}

## Install modules
- name: PHP5 | Install PHP5 modules
  remote_user: wenba
  sudo: yes
  yum: name={{ item }} state={{ php5_yum_state }}
  with_items: php5_yum_modules
  when: php5_yum_modules is defined

## PHP5 | Apache2 configuration
- name: PHP5 | Backup configuration
  remote_user: wenba
  sudo: yes
  shell: creates=/etc/php.ini.orig cp /etc/php.ini /etc/php.ini.orig
  register: result
- fetch: src=/etc/php.ini.orig dest=fetched
  remote_user: wenba
  sudo: yes
  when: result|changed
- name: PHP5 | Deploy configuration 1
  remote_user: wenba
  sudo: yes
  copy: src=php.ini dest=/etc/php.ini mode=0644 owner=root group=root backup=yes
  register: result
- fetch: src=/etc/php.ini dest=fetched
  remote_user: wenba
  sudo: yes
  when: result|changed
- name: PHP5 | Deploy configuration 2
  remote_user: wenba
  sudo: yes
  copy: src=php-fpm.conf dest=/etc/php-fpm.conf mode=0644 owner=root group=root backup=yes
- name: PHP5 | Deploy configuration 3
  remote_user: wenba
  sudo: yes
  copy: src=www.conf dest=/etc/php-fpm.d/www.conf mode=0644 owner=root group=root backup=yes
- name: PHP5 | Deploy configuration 4
  remote_user: wenba
  sudo: yes
  file: path=/var/lib/php/session owner=wenba group=wenba mode=0660 recurse=yes
- name: PHP5 | Check service daemon
  service: name=php-fpm state=started enabled=yes
